/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bibliotecagrupo15.vistas;

import bibliotecagrupo15.accesoADatos.*;
import bibliotecagrupo15.entidades.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Chris
 */
public class EjemplaresView extends javax.swing.JInternalFrame {
    
    LibroData ld = new LibroData();
    AutorData ad = new AutorData();
    EjemplarData ed = new EjemplarData();
    
    /**
     * Creates new form LibrosView
     */
    
    public EjemplaresView() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbLibros = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jtfCantEjemplares = new javax.swing.JTextField();
        fondoLibros = new javax.swing.JLabel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(550, 350));
        setMinimumSize(new java.awt.Dimension(550, 350));
        setPreferredSize(new java.awt.Dimension(550, 350));
        setVisible(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(550, 328));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 328));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar ejemplares");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Libro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jcbLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 450, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad de ejemplares:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jtfCantEjemplares.setText("0");
        jPanel1.add(jtfCantEjemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 50, -1));

        fondoLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo15/vistas/imagenes/fondo-ejemplares.png"))); // NOI18N
        jPanel1.add(fondoLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLibrosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jcbLibrosActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        try{
            Libro libro = (Libro) jcbLibros.getSelectedItem();
            
            int cantEjemp = Integer.parseInt(jtfCantEjemplares.getText());
            
            if (cantEjemp >= 1 && cantEjemp <=50) {
                for (int i = 1; i <= cantEjemp; i++) {
                    Ejemplar ejemplar = new Ejemplar(libro, 0);
                    ed.crearEjemplar(ejemplar);
                }
                JOptionPane.showMessageDialog(this, "Ejemplares creados");
                jtfCantEjemplares.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese la cantidad de ejemplares a crear \n Máximo: 50");
            }
        }catch(java.lang.NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "La cantidad ingresada es incorrecta");
        }
            
            
    }//GEN-LAST:event_jbAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoLibros;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JComboBox<Libro> jcbLibros;
    private javax.swing.JTextField jtfCantEjemplares;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        List<Libro> libros = ld.listarLibros();
        for (Libro libro : libros) {
            jcbLibros.addItem(libro);
        }
    }

}
