/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bibliotecagrupo15.vistas;

import bibliotecagrupo15.accesoADatos.LectorData;
import bibliotecagrupo15.accesoADatos.PrestamoData;
import bibliotecagrupo15.entidades.Lector;
import bibliotecagrupo15.entidades.Libro;
import bibliotecagrupo15.entidades.Prestamo;
import java.awt.Color;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ListaPrestamos extends javax.swing.JInternalFrame {

    private DefaultTableModel tabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    /**
     * Creates new form ListaPrestamos
     */
    PrestamoData pd = new PrestamoData();
    LectorData ld = new LectorData();

    public ListaPrestamos() {
        initComponents();
        grupo();  
        buscar.setVisible(false);
        fecha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupob = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListaPrestamos = new javax.swing.JRadioButton();
        SociosActivos = new javax.swing.JRadioButton();
        LibrosPrestadosxFecha = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(520, 368));

        jPanel1.setPreferredSize(new java.awt.Dimension(520, 365));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido al Listado Administrativo de Prestamos ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Seleccione la vista que desea revisar: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        ListaPrestamos.setText("Lista de Prestamos ");
        ListaPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(ListaPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        SociosActivos.setText("Socios con Prestamos vencidos");
        SociosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SociosActivosActionPerformed(evt);
            }
        });
        jPanel1.add(SociosActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        LibrosPrestadosxFecha.setText("Lista de Libros Prestados por fecha");
        LibrosPrestadosxFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrosPrestadosxFechaActionPerformed(evt);
            }
        });
        jPanel1.add(LibrosPrestadosxFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        tablaP.setBackground(new java.awt.Color(87, 87, 86));
        tablaP.setForeground(new java.awt.Color(255, 255, 255));
        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tablaP.setOpaque(false);
        tablaP.setSelectionBackground(new java.awt.Color(136, 92, 8));
        tablaP.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaP);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 470, 180));

        jLabel3.setForeground(new java.awt.Color(179, 84, 14));
        jLabel3.setText("Esta ventana es solamente para dar un vistazo a la organizacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 480, -1));

        fecha.setBackground(new java.awt.Color(87, 87, 86));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 140, -1));

        buscar.setBackground(new java.awt.Color(87, 87, 86));
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibliotecagrupo15/vistas/imagenes/fondo-ListadoPrestamos.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaPrestamosActionPerformed
        // TODO add your handling code here:
        buscar.setVisible(false);
        fecha.setVisible(false);
        borrarcabecera();
        cargarCabecera1();
        cargarTabla1();
        ListaPrestamos.setEnabled(false);
        SociosActivos.setEnabled(true);
        LibrosPrestadosxFecha.setEnabled(true);
    }//GEN-LAST:event_ListaPrestamosActionPerformed

    private void SociosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SociosActivosActionPerformed
        // TODO add your handling code here:
        buscar.setVisible(false);
        fecha.setVisible(false);
        ListaPrestamos.setEnabled(true);
        SociosActivos.setEnabled(false);
        LibrosPrestadosxFecha.setEnabled(true);
        borrarcabecera();
        cargarCabecera2();
        cargarTabla2();
    }//GEN-LAST:event_SociosActivosActionPerformed

    private void LibrosPrestadosxFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrosPrestadosxFechaActionPerformed
        // TODO add your handling code here:
        ListaPrestamos.setEnabled(true);
        SociosActivos.setEnabled(true);
        LibrosPrestadosxFecha.setEnabled(false);
        borrarcabecera();
        cargarCabecera3();
        buscar.setVisible(true);
        fecha.setVisible(true);
        JOptionPane.showMessageDialog(this, "Ingrese una fecha con el calendario");

    }//GEN-LAST:event_LibrosPrestadosxFechaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        try {
            limpiar();
            java.util.Date f = fecha.getDate();
            java.sql.Date sql = new java.sql.Date(f.getTime());
            cargarTabla3(sql);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una fecha por favor");
        }

    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LibrosPrestadosxFecha;
    private javax.swing.JRadioButton ListaPrestamos;
    private javax.swing.JRadioButton SociosActivos;
    private javax.swing.JButton buscar;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.ButtonGroup grupob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaP;
    // End of variables declaration//GEN-END:variables

    private void grupo() {
        grupob.add(ListaPrestamos);
        grupob.add(SociosActivos);
        grupob.add(LibrosPrestadosxFecha);
    }

    private void limpiar() {
        int p = tablaP.getRowCount() - 1;
        for (; p >= 0; p--) {
            tabla.removeRow(p);
        }
    }

    private void borrarcabecera() {
        tabla.setColumnCount(0);
        tablaP.setModel(tabla);
    }

    private void cargarCabecera1() {
        tabla.addColumn("ID");
        tabla.addColumn("NRO SOCIO");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("FECHA DE INICIO");
        tabla.addColumn("VENCIMIENTO");
        tablaP.setModel(tabla);

    }

    private void cargarCabecera2() {
        tabla.addColumn("NRO SOCIO");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("MAIL");
        tablaP.setModel(tabla);

    }

    private void cargarCabecera3() {
        tabla.addColumn("TITULO");
        tabla.addColumn("AUTOR");
        tabla.addColumn("TIPO");
        tabla.addColumn("EDITORIAL");
        tabla.addColumn("AÑO");
        tablaP.setModel(tabla);

    }

    private void cargarTabla1() {
        Color color = new Color(87, 87, 86);
//Color color2=new Color(255,255,255);
        tablaP.setBackground(color);
//jTabla_registro.getTableHeader().setBackground(new Color(32, 136, 203));
        tablaP.getTableHeader().setBackground(color);
//tablaP.getTableHeader().setForeground(color2);
        limpiar();
        List<Prestamo> prestamos = pd.ListarPrestamos();
        for (Prestamo p : prestamos) {
            tabla.addRow(new Object[]{p.getIdPrestamo(), p.getLector().getSocio(), p.getLector().getNombre(), p.getFechaInicio(), p.getFechaFin()});
        }

    }

    private void cargarTabla2() {
        Color color = new Color(87, 87, 86);
//Color color2=new Color(255,255,255);
        tablaP.setBackground(color);
//jTabla_registro.getTableHeader().setBackground(new Color(32, 136, 203));
        tablaP.getTableHeader().setBackground(color);
//tablaP.getTableHeader().setForeground(color2);
        limpiar();
        List<Lector> l = pd.ListarLectoresxFechaVencida();
        for (Lector lec : l) {
            tabla.addRow(new Object[]{lec.getSocio(), lec.getNombre(), lec.getMail()});
        }

    }

    private void cargarTabla3(Date fecha) {
        Color color = new Color(87, 87, 86);
//Color color2=new Color(255,255,255);
        tablaP.setBackground(color);
//jTabla_registro.getTableHeader().setBackground(new Color(32, 136, 203));
        tablaP.getTableHeader().setBackground(color);
//tablaP.getTableHeader().setForeground(color2);
        limpiar();
        List<Libro> li = pd.ListarLibrosxFecha(fecha);
        for (Libro lib : li) {
            tabla.addRow(new Object[]{lib.getTitulo(), lib.getAutor(), lib.getTipo(), lib.getEditorial(), lib.getAnio()});
        }

    }
}
